DobreRece/urls.py
from django.contrib import admin
from django.urls import path, include

from charity import views
from charity.views import CategoryCreateView, DonationFormView, FormConfirmationView

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', views.LandingPageView.as_view(template_name='index.html'), name='index'),
    path('category/create/', CategoryCreateView.as_view(), name="create_category"),
    path('form/', DonationFormView.as_view(), name='form'),
    path('form_confirmation/', FormConfirmationView.as_view(), name='form_confirmation'),

    path("accounts/", include("accounts.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from accounts import views
from accounts.views import UserCreateView, LoginPageView, UserProfileView, LogoutPageView, UpdateUserView

urlpatterns = [
    path('login/', LoginPageView.as_view(), name='login'),
    path('logout/', LogoutPageView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('userprofile/', UserProfileView.as_view(), name='userprofile'),
    path('editprofile/<int:pk>', UpdateUserView.as_view(), name='editprofile'),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path("password_reset/", views.password_reset_request, name="password_reset"),
]

charity/models.py
from django.contrib.auth.models import User
from django.db import models

from charity.constants import Institutions


class Category(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Institution(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    type = models.PositiveSmallIntegerField(choices=Institutions.Choices, default=Institutions.Choices[0][0])
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return self.name

    @property
    def category_ids(self):
        return ','.join([str(x.id) for x in self.categories.all()])


class Donation(models.Model):
    quantity = models.SmallIntegerField()
    categories = models.ManyToManyField(Category)
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    address = models.CharField(max_length=256)
    phone_number = models.CharField(max_length=56)
    city = models.CharField(max_length=56)
    zip_code = models.CharField(max_length=56)
    pick_up_date = models.DateField(null=True)
    pick_up_time = models.TimeField(null=True)
    pick_up_comment = models.CharField(max_length=512)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'By user: {self.user.username}, quantity: {self.quantity}, shipment address: {self.address}'

templates/EditUser.html
{% extends "base.html" %}

{% block content %}
    <div align="center">
        <h2>Edytuj dane: </h2>
        <form method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="form-group">
                {{ form.first_name.errors }}
                {{ form.first_name }}
            </div>
            <div class="form-group">
                {{ form.last_name.errors }}
                {{ form.last_name }}
            </div>
            <div class="form-group">
                {{ form.email.errors }}
                {{ form.email }}
            </div>
            <div align="center" class="form-group">
                <button type="submit" value="Prześlij" class="btn">Prześlij</button>
            </div>
            <div></div>
        </form>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="pl">
{% load static %}
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <title>Dobre Ręce</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}"/>
</head>
<body>
<header>
    <nav class="container container--70">
        <ul class="nav--actions">
            {% if user.is_authenticated %}
                <li class="logged-user">
                    Witaj {{ user.username }}
                    <ul class="dropdown">
                        <li><a href="{% url 'userprofile' %}" class="btn btn--small btn--without-border">Profil
                            użytkownika</a></li>
                        {% if user.is_staff %}
                            <li><a href="/admin/" class="btn btn--small btn--without-border">Panel admina</a></li>
                        {% endif %}
                        <li><a href="{% url 'logout' %}" class="btn btn--small btn--without-border">Wyloguj</a></li>
                    </ul>
                </li>
            {% else %}
                <li><a href="{% url 'login' %}" class="btn btn--small btn--without-border">Zaloguj</a></li>
            {% endif %}

            {% if not user.is_authenticated %}
                <li><a href="{% url 'register' %}" class="btn btn--small btn--highlighted">Załóż konto</a></li>

            {% endif %}
        </ul>
        <ul>
            <li><a href="{% url "index" %}" class="btn btn--without-border active">Start</a></li>
            <li><a href="{% url "index" %}#steps" class="btn btn--without-border">O co chodzi?</a></li>
            <li><a href="{% url "index" %}#about-us" class="btn btn--without-border">O nas</a></li>
            <li><a href="{% url "index" %}#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
            <li><a href="{% url 'form' %}" } class="btn btn--without-border">Przekaż dary</a></li>
            <li><a href="#contact" class="btn btn--without-border">Kontakt</a></li>
        </ul>
    </nav>

    <section id="content">
        {% block content %}
        {% endblock %}
    </section>

    <footer>
        <div id="contact" class="contact">
            <h2>Skontaktuj się z nami</h2>
            <h3>Formularz kontaktowy</h3>
            <form class="form--contact">
                <div class="form-group form-group--50"><input type="text" name="name" placeholder="Imię"/></div>
                <div class="form-group form-group--50"><input type="text" name="surname" placeholder="Nazwisko"/></div>

                <div class="form-group"><textarea name="message" placeholder="Wiadomość" rows="1"></textarea></div>

                <button class="btn" type="submit">Wyślij</button>
            </form>
        </div>
        <div class="bottom-line">
            <span class="bottom-line--copy">Copyright &copy; 2019</span>
            <div class="bottom-line--icons">
                <a href="#" class="btn btn--small"><img src="{% static "images/icon-facebook.svg" %}"/></a>
                <a href="#" class="btn btn--small"><img src="{% static "images/icon-instagram.svg" %}"/></a>
            </div>
        </div>
    </footer>

    <script src="{% static 'js/app.js' %}"></script>
</body>
</html>

templates/category_form.html
{% extends "base.html" %}

{% block content %}

    <form action='' method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>

{% endblock %}

templates/form-confirmation.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="slogan container container--90">
        <h2>
            Dziękujemy za przesłanie formularza Na maila prześlemy wszelkie
            informacje o odbiorze.
        </h2>
    </div>
    </header>

{% endblock %}

templates/form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <div class="slogan container container--90">
        <div class="slogan--item">
            <h1>
                Oddaj rzeczy, których już nie chcesz<br/>
                <span class="uppercase">potrzebującym</span>
            </h1>

            <div class="slogan--steps">
                <div class="slogan--steps-title">Wystarczą 4 proste kroki:</div>
                <ul class="slogan--steps-boxes">
                    <li>
                        <div><em>1</em><span>Wybierz rzeczy</span></div>
                    </li>
                    <li>
                        <div><em>2</em><span>Spakuj je w worki</span></div>
                    </li>
                    <li>
                        <div><em>3</em><span>Wybierz fundację</span></div>
                    </li>
                    <li>
                        <div><em>4</em><span>Zamów kuriera</span></div>
                    </li>
                </ul>
            </div>
        </div>
    </div>


    <section class="form--steps">
        <div class="form--steps-instructions">
            <div class="form--steps-container">
                <h3>Ważne!</h3>
                <p data-step="1" class="active">
                    Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
                    wiedzieć komu najlepiej je przekazać.
                </p>
                <p data-step="2">
                    Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
                    wiedzieć komu najlepiej je przekazać.
                </p>
                <p data-step="3">
                    Wybierz jedną, do
                    której trafi Twoja przesyłka.
                </p>
                <p data-step="4">Podaj adres oraz termin odbioru rzeczy.</p>
            </div>
        </div>

        <div class="form--steps-container">
            <div class="form--steps-counter">Krok <span>1</span>/5</div>

            {# -----------------------------------------------------------------------------------------------------#}
            <form action="{% url "form" %}" method="post">
                {% csrf_token %}

                <!-- STEP 1: class .active is switching steps -->
                <div data-step="1" class="active">
                    <h3>Zaznacz co chcesz oddać:</h3>
                    {% for category in form.categories.field.queryset.all %}
                        <div class="form-group form-group--checkbox">

                            <label>
                                <input
                                        type="checkbox"
                                        name="categories"
                                        value="{{ category.id }}"
                                />
                                <span class="checkbox"></span>
                                <span class="description"
                                >{{ category.name }} </span>
                            </label>
                        </div>
                    {% endfor %}


                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn next-step">Dalej</button>
                    </div>
                </div>

                <!-- STEP 2 -->
                <div data-step="2">
                    <h3>Podaj liczbę 60l worków, w które spakowałeś/aś rzeczy:</h3>

                    <div class="form-group form-group--inline">
                        <label>
                            Liczba 60l worków:
                            <input type="number" name="quantity" step="1" min="1"/>
                        </label>
                    </div>

                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn prev-step">Wstecz</button>
                        <button type="button" class="btn next-step">Dalej</button>
                    </div>
                </div>


                <!-- STEP 3 -->
                <div data-step="3">
                    <h3>Wybierz organizacje, której chcesz pomóc:</h3>


                    {% for institution in form.institution.field.queryset.all %}
                        <div class="form-group form-group--checkbox">
                            <label>
                                <input type="radio" name="institution"
                                       data-category-ids="{{ institution.category_ids }}" value="{{ institution.id }}"/>
                                <span class="checkbox radio"></span>
                                <span class="description">
                  <div class="title">{{ institution.name }}</div>
                  <div class="subtitle">
                    {{ institution.description }}
                  </div>
                </span>
                            </label>
                        </div>
                    {% endfor %}

                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn prev-step">Wstecz</button>
                        <button type="button" class="btn next-step">Dalej</button>
                    </div>
                </div>

                <!-- STEP 4 -->
                <div data-step="4">
                    <h3>Podaj adres oraz termin odbioru rzecz przez kuriera:</h3>

                    <div class="form-section form-section--columns">
                        <div class="form-section--column">
                            <h4>Adres odbioru</h4>
                            <div class="form-group form-group--inline">
                                <label> Ulica <input type="text" name="address"/> </label>
                            </div>

                            <div class="form-group form-group--inline">
                                <label> Miasto <input type="text" name="city"/> </label>
                            </div>

                            <div class="form-group form-group--inline">
                                <label>
                                    Kod pocztowy <input type="text" name="zip_code"/>
                                </label>
                            </div>

                            <div class="form-group form-group--inline">
                                <label>
                                    Numer telefonu <input type="phone" name="phone_number"/>
                                </label>
                            </div>
                        </div>

                        <div class="form-section--column">
                            <h4>Termin odbioru</h4>
                            <div class="form-group form-group--inline">
                                <label> Data <input type="date" name="pick_up_date"/> </label>
                            </div>

                            <div class="form-group form-group--inline">
                                <label> Godzina <input type="time" name="pick_up_time"/> </label>
                            </div>

                            <div class="form-group form-group--inline">
                                <label>
                                    Uwagi dla kuriera
                                    <textarea name="pick_up_comment" rows="5"></textarea>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn prev-step">Wstecz</button>
                        <button type="button" class="btn next-step">Dalej</button>
                    </div>
                </div>

                <!-- STEP 5 -->
                <div data-step="5">
                    <h3>Podsumowanie Twojej darowizny</h3>

                    <div class="summary">
                        <div class="form-section">
                            <h4>Oddajesz:</h4>
                            <ul>
                                <li>
                                    <span class="icon icon-bag"></span>
                                    <span class="summary--text"
                                    ></span
                                    >
                                </li>

                                <li>
                                    <span class="icon icon-hand"></span>
                                    <span class="summary--text"
                                    ></span
                                    >
                                </li>
                            </ul>
                        </div>

                        <div class="form-section form-section--columns">
                            <div class="form-section--column" class="summary--text">
                                <h4>Adres odbioru:</h4>
                                <ul>
                                    <li id="address">Prosta 51</li>
                                    <li id="city">Warszawa</li>
                                    <li id="postcode">99-098</li>
                                    <li id="phone">123 456 789</li>
                                </ul>
                            </div>

                            <div class="form-section--column">
                                <h4>Termin odbioru:</h4>
                                <ul>
                                    <li id="data">13/12/2018</li>
                                    <li id="time">15:40</li>
                                    <li id="info">Brak uwag</li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn prev-step">Wstecz</button>
                        <button type="submit" class="btn">Potwierdzam</button>
                    </div>
                </div>

            </form>
        </div>
    </section>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
    <header class="header--main-page">

        <div class="slogan container container--90">
            <div class="slogan--item">
                <h1>
                    Zacznij pomagać!<br/>
                    Oddaj niechciane rzeczy w zaufane ręce
                </h1>
            </div>
        </div>
    </header>

    <section id="stats" class="stats">
        <div class="container container--85">
            <div class="stats--item">
                <em>{{ donation_counter }}</em>
                <h3>Oddanych worków</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius est beatae, quod accusamus illum
                    tempora!</p>
            </div>

            <div class="stats--item">
                <em>{{ institution_counter }}</em>
                <h3>Wspartych organizacji</h3>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam magnam, sint nihil cupiditate
                    quas quam.</p>
            </div>

        </div>
    </section>

    <section id="steps" class="steps">
        <h2>Wystarczą 4 proste kroki</h2>

        <div class="steps--container">
            <div class="steps--item">
                <span class="icon icon--hands"></span>
                <h3>Wybierz rzeczy</h3>
                <p>ubrania, zabawki, sprzęt i inne</p>
            </div>
            <div class="steps--item">
                <span class="icon icon--arrow"></span>
                <h3>Spakuj je</h3>
                <p>skorzystaj z worków na śmieci</p>
            </div>
            <div class="steps--item">
                <span class="icon icon--glasses"></span>
                <h3>Zdecyduj komu chcesz pomóc</h3>
                <p>wybierz zaufane miejsce</p>
            </div>
            <div class="steps--item">
                <span class="icon icon--courier"></span>
                <h3>Zamów kuriera</h3>
                <p>kurier przyjedzie w dogodnym terminie</p>
            </div>
        </div>

        <a href="{% url 'register' %}" class="btn btn--large">Załóż konto</a>
    </section>

    <section id="about-us" class="about-us">
        <div class="about-us--text">
            <h2>O nas</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas vitae animi rem pariatur incidunt
                libero optio esse quisquam illo omnis.</p>
            <img src="{% static "images/signature.svg" %}" class="about-us--text-signature" alt="Signature"/>
        </div>
        <div class="about-us--image"><img src="{% static "/images/about-us.jpg" %}" alt="People in circle"/></div>
    </section>

    <section id="help" class="help">
        <h2>Komu pomagamy?</h2>

        <ul class="help--buttons">
            <li data-id="1"><a href="#" class="btn btn--without-border active">Fundacjom</a></li>
            <li data-id="2"><a href="#" class="btn btn--without-border">Organizacjom pozarządowym</a></li>
            <li data-id="3"><a href="#" class="btn btn--without-border">Lokalnym zbiórkom</a></li>
        </ul>

        <!-- SLIDE 1 -->
        <div class="help--slides active" data-id="1">
            <p>W naszej bazie znajdziesz listę zweryfikowanych Fundacji, z którymi współpracujemy. Możesz sprawdzić czym
                się zajmują, komu pomagają i czego potrzebują.</p>

            <ul class="help--slides-items">
                {% for foundation in foundations %}
                    <li>
                        <div class="col">
                            <div class="title">{{ foundation.name }}</div>
                            <div class="subtitle">{{ foundation.description }}</div>
                            `</div>

                        <div class="col">
                            <div class="text">
                                {% for category in foundation.categories.all %}
                                    {{ category.name }}
                                {% endfor %}
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>




        <!-- SLIDE 2 -->
        <div class="help--slides" data-id="2">
            <p>
                Oranizacje pozarządowe, które chcą wspierać siebie i innych!
            </p>
            <ul class="help--slides-items">
                {% for ngo in ngos %}
                    <li>
                        <div class="col">
                            <div class="title">{{ ngo.name }}</div>
                            <div class="subtitle">{{ ngo.description }}</div>
                        </div>

                        <div class="col">
                            <div class="text">
                                {% for category in ngo.categories.all %}
                                    {{ category.name }}
                                {% endfor %}
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>



        </div>

        <!-- SLIDE 3 -->
        <div class="help--slides" data-id="3">
            <p>Lokalne zbiórki zorganizowane przez lokalne społeczności.</p>
            <ul class="help--slides-items">
                {% for collection in local_collections %}
                    <li>
                        <div class="col">
                            <div class="title">{{ collection.name }}</div>
                            <div class="subtitle">{{ collection.description }}</div>
                        </div>

                        <div class="col">
                            <div class="text">
                                {% for category in collection.categories.all %}
                                    {{ category.name }}
                                {% endfor %}
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>


        </div>
    </section>

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block content %}

    <section class="login-page">
        <h2>Zaloguj się</h2>

        <form method="post" action="{% url "login" %}">
            {% csrf_token %}
            <div class="form-group">
                <input type="email" name="username" placeholder="Email"/>
            </div>
            <div class="form-group">
                <input type="password" name="password" placeholder="Hasło"/>
                <a href="{% url "password_reset" %}" class="btn btn--small btn--without-border reset-password">Przypomnij
                    hasło</a>
            </div>

            <div class="form-group form-group--buttons">
                <a href="#" class="btn btn--without-border">Załóż konto</a>
                <button class="btn" type="submit">Zaloguj się</button>
            </div>
        </form>
    </section>

{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block content %}

    <section class="login-page">
        <h2>Załóż konto</h2>
        <form method="post" action="{% url "register" %}">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="form-group">
                {{ form.first_name.errors }}
                {{ form.first_name }}
            </div>
            <div class="form-group">
                {{ form.last_name.errors }}
                {{ form.last_name }}
            </div>
            <div class="form-group">
                {{ form.email.errors }}
                {{ form.email }}
            </div>

            <div class="form-group">
                {{ form.password1.errors }}
                {{ form.password1 }}
            </div>


            <div class="form-group">
                {{ form.password2.errors }}
                {{ form.password2 }}
            </div>

            <div class="form-group form-group--buttons">
                <a href="{% url "login" %}" class="btn btn--without-border">Zaloguj się</a>
                <button class="btn" type="submit">Załóż konto</button>
            </div>
        </form>
    </section>

{% endblock %}

templates/user-profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <section class="container--90">

        <div align="center">

            <h2>Konto użytkowniczki(ka) {{ user.username }}</h2>
            <a style="color:gray" href="{% url 'editprofile' user.id %}">Zmień dane</a>

            <h1>Imię: {{ user.first_name }} </h1>
            <h1>Nazwisko: {{ user.last_name }}</h1>
            <h1>Email: {{ user.email }}</h1>
            <h2></h2>
            <div align="center">
                <h1>Lista darów użytkownika:</h1>

                {% for donation in user.donation_set.all %}
                    <h1>Dar {{ donation.id }}:</h1>
                    <ul style="color:gray;font-size:20px">
                        <li>ilość worków: {{ donation.quantity }}</li>
                        <li>przekazane do: {{ donation.institution }}</li>
                        <li>
                            rodzaj darów:
                            {% for category in donation.categories.all %}
                                {{ category.name }}
                            {% endfor %}
                        </li>
                        <li> data odbioru dnia {{ donation.pick_up_date }}, o
                            godzinie {{ donation.pick_up_time }}</li>
                    </ul>
                {% endfor %}
            </div>
        </div>
        <h2></h2>
    </section>

{% endblock %}